### ISSUE TITLE
Search Table: Only the first selected line is copied to clipboard

### ISSUE THREAD

**Issue by marc-heinlein** [COVESA/dlt-viewer#224]
**Precondition:**
- dlt-viewer 2.21.2, have some .dlt-file loaded
- perform a search (via search bar or search dialog)

**Action:**
- select some lines in the resulting search table (as a block, or some single lines)
- copy selected lines to clipboard (Ctrl-C or context menu "Copy Selection (Payload) to Clipboard")

**Expected behavior:**
- All selected lines are copied

**Actual behavior:**
- Only the first (lowest Index) of the selected lines is copied

**Comment by alexmucde** [comment]
Tried to reproduce this isse in DLT Viewer Version 2.21.3 in Windows, but issue is not reproducible, Selecting several lines and copying to Clipboard works.

@marc-heinlein Which OS are you using? Can you reproduce the issue with 2.21.3?

**Comment by marc-heinlein** [comment]
Hello @alexmucde, here is the OS specification:
```
Edition	Windows 10 Enterprise
Version	20H2
Installiert am	09.02.2021
Betriebssystembuild	19042.746
Leistung	Windows Feature Experience Pack 120.2212.551.0
```

DLT Viewer 2.21.2 was built with Qt 5.15.0 using gcc-8.1.0

We will check with latest DLT Viewer from master.

**Comment by marc-heinlein** [comment]
The bug was caused by an errorneous dll. Issue can be closed

**Comment by alexmucde** [comment]
@marc-heinlein Do you still know which dll was causing the issue? We have now another issue, which sounds similar #243
