### ISSUE TITLE
Copy selected messages formatted as Jira table to clipboard? 

### ISSUE THREAD

**Issue by SvenLuebke** [COVESA/dlt-viewer#234]
Dear dlt-viewer developers!

Is a clipboard export of selected Dlt messages formatted as Jira table (in context menu) too specialized? I could provide a PR for that if somebody is interested...

BR,
Sven

**Comment by alexmucde** [comment]
Hi Sven,

yes this feature looks interesting, this is a common use case. please provide a PR.

    Alex

**Comment by alexmucde** [comment]
@SvenLuebke Is there still an activity form your side? If not i will close this issue.

**Comment by SvenLuebke** [comment]
@alexmucde Please don't close this issue! I have to discuss this with the company I'm working at and didn't have time to do it yet.

**Comment by SvenLuebke** [comment]
@alexmucde Are you able to explain the following text?:

Every contribution must carry the following sign-off line with your real name and email address:
"Signed-off-by: Firstname Lastname <[firstname.lastname@example.com](mailto:firstname.lastname@example.com)>"

Where do I have to add this sign-off line?

**Comment by SvenLuebke** [comment]
Created [PR#276](https://github.com/COVESA/dlt-viewer/pull/276)
