### ISSUE TITLE
bool args are persisted without DLT_TYLE_8BIT

### ISSUE THREAD

**Issue by mbehr1** [COVESA/dlt-viewer#242]
Bool args are persisted with a TYLE of 0 which is not fulfilling
dlt autosar spec: [Dlt139] ⌈Type Length (TYLE) shall be 1. ⌋

This causes e.g. the Wireshark DLT dissector to fail on parsing the payload.

Wrong code is here:
https://github.com/COVESA/dlt-viewer/blob/03baa67d3bb059458cb5b8e0ed940ea6f607f575/qdlt/qdltargument.cpp#L312

I guess a | DLT_TYLE_8BIT would be sufficient to fix.

Shall I send a PR?

**Comment by mbehr1** [comment]
@alexmucde @gernotmuc fyi.

**Comment by alexmucde** [comment]
@mbehr1 

Yes that's right. I would change the following line 333:

if((typeInfo == DltTypeInfoSInt) || (typeInfo == DltTypeInfoUInt) || (typeInfo == DltTypeInfoFloa) **|| (typeInfo == DltTypeInfoBool)**) {

If data size is 1, this would add dltType |= DLT_TYLE_8BIT;

Yes you can provide a PR.

**Comment by mbehr1** [comment]
fixed wit #247
