### ISSUE TITLE
Release artifacts not present in releases page, is this expected?

### ISSUE THREAD

**Issue by GianlucaAgl** [COVESA/dlt-viewer#261]
It seems from changelogs and closed PRs that compiled binaries should be present in GitHub release page, but currently no binary is listed there https://github.com/COVESA/dlt-viewer/releases

Eg.
![image](https://user-images.githubusercontent.com/101354770/157723527-02fa5dd4-30e7-419b-a1e4-ca898d365910.png)

I was expecting to find the binary after having seen PR #187, that was integrated in Release v2.21.2 . Also the install.md file in scripts/ folder reports that, for example in the windows folder (at least in master branch):
https://github.com/COVESA/dlt-viewer/blob/master/scripts/windows/install.md

Is this currently only a plan for the next release? Or is this an error?

I have not seen any official announcement, so this is just a question to understand if it's possible to obtain the binaries without dealing with Qt framework SDK, now or in the future.

Thank you,
Gianluca

**Comment by alexmucde** [comment]
@GianlucaAgl We use Github Action to test PR builds. Release Artifacts should be also generated, but this is currently not working. Need some help to fix this, as i am not familiar with this.

**Comment by alexmucde** [comment]
Any help from the community?

**Comment by Usha-Rajanna** [comment]
@GianlucaAgl  Sorry we have not planned to release any binaries for now. But we have CI artifacts available. Please check the attachements. Thank you.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/110012570/198580481-5b2e8e28-0b3c-4625-93c0-c92398275708.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/110012570/198580609-11e6e2c4-e803-4f31-9259-c4b42dbc3d24.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/110012570/198580739-b2ad6363-ac0c-4605-81dc-74289c8f032f.png)

**Comment by Usha-Rajanna** [comment]
Wont be fixed
