### ISSUE TITLE
Ability for send serial message in Serial ASCII Mode?

### ISSUE THREAD

**Issue by beidouchangxi** [COVESA/dlt-viewer#262]
With Serial ASCII Mode I can actually use DLT viewer as a powerful serial debug tool.
The only downside is I cannot send a message by DLT viewer.
Is it possible for add this feature?

**Comment by beidouchangxi** [comment]
Yes, I mean provide a dialog for send commands to ECU in Serial ASCII Mode, a plugin will be pretty enough to do it.
But I took a look on the API documentm, it seems like no API can provide this ability?

Another idea is use the existing "Send Injection" dialog, which is currently doing nothing in Serial ASCII Mode.

**Comment by beidouchangxi** [comment]
I trying to look into code about how to do it but I am not familar with cpp and QT,
If I am lucky maybe I can provide a PR, are you interested in this PR?

**Comment by beidouchangxi** [comment]
a PR is created based on "Send Injection" dialog

**Comment by alexmucde** [comment]
Great thanks

**Comment by alexmucde** [comment]
PR is integrated
