### ISSUE TITLE
Installable or installable programs are provided

### ISSUE THREAD

**Issue by MaybenYi** [COVESA/dlt-viewer#277]
Whether you can provide installable and install-free programs to re-build from code is more dependent on the environment

**Comment by alexmucde** [comment]
@MaybenYi There are some executables generated with each commit or pull request, which you can download. Please check if this is enough for you.

**Comment by alexmucde** [comment]
Provide Executables with every Release.

**Comment by alexmucde** [comment]
Please check lattest Release v2.23.0
