### ISSUE TITLE
"set all active" / "set all inactive" in context menu for Filter is not working

### ISSUE THREAD

**Issue by firedevil79** [COVESA/dlt-viewer#279]
used version: 
![image](https://user-images.githubusercontent.com/70649483/179704355-bb36d902-6bd5-4c49-9da5-3569fe9dcf17.png)

added a couple of filter with different content. 

right click on the "activate" Filter box.
select "set all active"

reaction: 
only the filter is getting active where the mouse is pointing to when selecting the right click context menu

expected:
all filter shall be active or inactive when the right click context menu is used.

**Comment by alexmucde** [comment]
@firedevil79 I tried it, looks like a feature. If you select all filters and the press "set all active" it works.

**Comment by alexmucde** [comment]
Fixed name by #306
