### ISSUE TITLE
Filter color setting is not applied when the second color is same APP (application) ID, but different CT (context) ID

### ISSUE THREAD

**Issue by firedevil79** [COVESA/dlt-viewer#280]
![image](https://user-images.githubusercontent.com/70649483/179708158-381c8860-4554-4f0c-8181-efbfb58a1399.png)

precondition:
there are multiple filters in the project

Filter 1:  (all Tuner messages shall be in red)
color setting: red
AppID: TUNE
CT ID: empty 

Filter 2: (Tuner API shall be shown in green)
color setting: green
AppID: TUNE
CT ID; API

check DLT

only Filter 1 color is shown

I would expect the Filter 2 can also be added so I can see all messages for TUNE on red, but TUNE -> API in green

I think its kind of "priority" or hierarchy  setting needed of same APP ID but empty CT ID
also it depends on where the empty "CT ID" Filter is located. 
if the Filter 1 is on the bottom then it works as expected. 

means: 
Mark All Tuner with CTID "API" in green, mark all others in Tuner in red

**Comment by eengnr** [comment]
Filters are applied from bottom to top. That's why it works if your Filter 2 is above Filter 1.

**Comment by alexmucde** [comment]
@firedevil79 Marking of messages depends on the order. Thefirst filter which matches from top wins.
