### ISSUE TITLE
Make is not working in the new release

### ISSUE THREAD

**Issue by Halfgeek0** [COVESA/dlt-viewer#285]
The make command gives the below error in the latest release
commit SHA 9206b0b4ec41a134de02cbab28d35c2da24f241c

../../src/mainwindow.cpp: In lambda function:
../../src/mainwindow.cpp:6748:47: error: no matching function for call to ‘QProcess::startDetached(qint64*)’
                     process.startDetached(&pid);

**Comment by alexmucde** [comment]
@Halfgeek0 We do not know any issues. Is it possible that you are using Qt6, which is not supported yet?

**Comment by Usha-Rajanna** [comment]
@Halfgeek0 can you please specify the platform you are using,  if Linux please use 20.04 Ubuntu

**Comment by Usha-Rajanna** [comment]
@Halfgeek0 Can you please tell us the platform you are using , if it is Linux use 20.04 Ubuntu.
I hope this should solve your problem.

**Comment by alexmucde** [comment]
No answer, consider it is already solved. Please reopen if needed.

**Comment by tt1m0n** [comment]
I have same problem. How possible fix this issues using Ubuntu 18.04

**Comment by Usha-Rajanna** [comment]
@tt1m0n As we have updated the Source to Support 20.04 and very soon it will be supporting  QT 6, please update both qt and Linux version. 
Thank you
