### ISSUE TITLE
How to append multiple dlt files into 1 dlt file

### ISSUE THREAD

**Issue by HaoLiuwide** [COVESA/dlt-viewer#290]
In our project, multiple dlt files are transferred to us to analyze. But dlt-viewer can only append dlt file one by one. We simply read all dlt file in "rb" format and put them together. Most time this method works fine, but sometimes filter function does not work to the jointed dlt file. What is the proper way to do the combination of multiple dlt logs?

thx!

**Comment by alexmucde** [comment]
@HaoLiuwide You can open several DLT files at once in the DLT Viewer by drag&drop or in the Open Dialog. What else do you want?

**Comment by alexmucde** [comment]
No answer, please reopen if not solved yet.
