### ISSUE TITLE
Home page at https://at.projects.genivi.org/wik not responding

### ISSUE THREAD

**Issue by bovirus** [COVESA/dlt-viewer#295]
@Usha-Rajanna 

The home page at at.project.,org  

https://at.projects.genivi.org/wiki/display/PROJ/Diagnostic+Log+and+Trace

not responding

**Comment by alexmucde** [comment]
Old hompages from Genivi are not availabel anymore. These pages existed long time ago before moving from git to github.

**Comment by alexmucde** [comment]
Fixed by #305
