### ISSUE TITLE
Linefeeds or Cariage Return in corrupted DLT causes CSV export inconsistency

### ISSUE THREAD

**Issue by tomasdrozdskodaauto** [COVESA/dlt-viewer#299]
Some corrupted DLT files might contain some Linefeeds or Cariage Return for example in EcuId, AppId or CtxId. This causes a line wrap. When exporting to CSV, the number of columns is not correct in some lines. This makes the CSV unusable in some applications.

Perhaps during Export all Linefeeds and Carriage Return should be removed.

![DLT_corrupted](https://user-images.githubusercontent.com/105794928/203042612-18677f79-0dbb-45a6-8645-8f211f114ac6.png)

![CSV_corrupted](https://user-images.githubusercontent.com/105794928/203042976-395c453b-e00d-404b-a640-6870c9c2c556.jpg)

**Comment by alexmucde** [comment]
Must be fixed by removing linefeeds and cariage returns in EcuId, AppId and CtxId before Export.

**Comment by alexmucde** [comment]
@tomasdrozdskodaauto Found solution please check attached PR

**Comment by tomasdrozdskodaauto** [comment]
Thank you for the pull request. I will test it in the new release.
