### ISSUE TITLE
Easy viewing of long payloads

### ISSUE THREAD

**Issue by ThomasManz** [COVESA/dlt-viewer#312]
Thanks for the great project, like it! :)

There´s only one little thing I´m missing right now:
when there is a long payload (longer than the width of the window) then it seems there is no simple way to view the full payload in the tool. The simplest way I found was just to copy it and paste it in a separate text editor.
How about opening a simple pop-up text box on double-click?
Maybe a prettier and more advanced option (and more effort) could be to change the bottom section (where now only the "search results" are located) to a "tab box" (like the Config, Plugin, Filter box on the left). Then one tab could be "Search results" and then a second tab could be "Selected message details" where all details and the full payload of the currently selected message could be shown.

**Comment by alexmucde** [comment]
@ThomasManz This feature is already available. You have to enable and show the DLT Viewer Plugin, then you will get a tab, which shows the full content of the current open DLT message.

**Comment by ThomasManz** [comment]
Awesome!!! Just as I´ve imagined it!
Thank you very much!
