### ISSUE TITLE
Binding Failed in UDP Connection

### ISSUE THREAD

**Issue by sathyan1997** [COVESA/dlt-viewer#313]
The UDP interface  Connection  with Target IP and Target Source port is given results in ECU Connection Binding Fault
(UDP Transmission is proper confirmed via Wireshark) what will be the reason behind this scenario?

**Comment by alexmucde** [comment]
@sathyan1997 We have not identified any issues with UDP with the lattest version on master.

Please check to configure as receiving interface the interface name, not the IP address. There was a change some time ago.

**Comment by alexmucde** [comment]
@sathyan1997 This should be fixed now. Binding to Multicast was removed. Please try lattest version on master and close ticket if fixed for you.

**Comment by alexmucde** [comment]
Fixed already on master
