### ISSUE TITLE
With Qt6, payload with specific emoji, fails to render and make the line unreadable.

### ISSUE THREAD

**Issue by Elastino** [COVESA/dlt-viewer#327]
When DLT payload *contains* this emoji, ⚠️, Qt6 fails to render whole payload in Main tableview, Search view and DLT Plugin view. 

## Patches
Applying replace to ⚠️ to !(non-emoji) in _tablemodel.cpp:251_ and _searchtablemodel.cpp:166_, fixed the issue.
So far, only this emoji, ⚠️, affects display issue while other emoji likes 🚫 and ✅ displayed correctly.
It appears to be a problem in Qt6.4.2 but this information is shared as hot fix to the issue.
```
visu_data = msg.toStringPayload().trimmed().replace("⚠️","!");
```

## Before
<img width="920" alt="before" src="https://user-images.githubusercontent.com/8371666/212363875-e445de2b-c26d-43c0-9fc5-bfe9747b5bed.png">

## After
<img width="1166" alt="after" src="https://user-images.githubusercontent.com/8371666/212363940-6b8f53b4-01cd-48e3-a402-039656ac638c.png">

**Comment by Elastino** [comment]
I forgot to mention that this is confirmed on Apple M1 with Ventura 13.1 and Qt6.4.2.

**Comment by Elastino** [comment]
Confirmed to be a bug in Qt6.4.2 where **_unqualified_** emoji breaks whole line as unreadable.
I filed a QtBug, https://bugreports.qt.io/browse/QTBUG-110159

**Comment by alexmucde** [comment]
@Elastino Thanks for the bug report. Can you also provide a PR, this will speed up the workaround?

**Comment by Elastino** [comment]
Qt responded back that they need minimal example to reproduce the issue.
Minimal example is provided to Qt Bug ticket system, and progressed back to Reported stage.

https://bugreports.qt.io/browse/QTBUG-110159

**Comment by alexmucde** [comment]
@Elastino Can you close the ticket?

**Comment by Elastino** [comment]
This is not an issue of DLT-Viewer. Should be tracked in QTBUG for QT.
