### ISSUE TITLE
With Qt6, Messages with APID less than 4 characters are not applied as filter.

### ISSUE THREAD

**Issue by Elastino** [COVESA/dlt-viewer#328]
**Source Code**
qdltfilter.cpp:181
`
if( (true == enableApid) && (msg.getApid() != apid))
{
    return false;
}
`

**With Qt5**
msg.getApid().length returns 2 or 3 if length is shorter than 4. 

**With Qt6.4.2**
msg.getApid().length returns always 4 thus it fails to compare against given _apid_, then fails to add the message.
It results message is not displayed in tableview. 

**Temporary Workaround**
It appears to be working fine with **.contains()** method.
`msg.getApid().contains(apid)`
However, this will make the filter pass all AA?? with just AA apid.

**Comment by alexmucde** [comment]
@Elastino Thanks for the bug report. I am wondering what is the reason, why the length information is wrong?

[QString.length()](https://doc.qt.io/qt-6/qstring.html#length)
Returns the number of characters in this string. Equivalent to [size](https://doc.qt.io/qt-6/qstring.html#size)().

Could it be, that there are some spaces in your used ApId?

**Comment by alexmucde** [comment]
I have tried the following with Qt 6.4.1:

    QString id("ABC");
    int length = id.length();
    QString id2("ABCD");
    int length2 = id2.length();

length is 3 and length2 is 4.

I see no issues with Qt6.

**Comment by alexmucde** [comment]
Provided Pull Request, please check.
