### ISSUE TITLE
How to apply parser to decode logfiles (Non Verbose Mode Plugin) by command line

### ISSUE THREAD

**Issue by Znzero** [COVESA/dlt-viewer#344]
![image](https://user-images.githubusercontent.com/41746380/218924050-4c01c934-acac-4434-9761-1bfd408174d2.png)
i have many logfiles in nonverbose mode, how do i use command line to decode those logfiles?

**Comment by alexmucde** [comment]
@Znzero

Option1: There is currently no command line interface for the non verbose plugin to load a configuration. But you can create and save a project, where you have enabled the plugin and you have loaded a Fibex file. Then load this project file by commandline.

Option2: The plugin must be extended to support the QDltPluginCommandInterface, then it would be also possible to provide the fibex file by commandline.

Can you work with Option1 or should we extend the plugin to support also Option2?

**Comment by alexmucde** [comment]
@Znzero If your question is answered please close the ticket. If you tend to option 2, we can keep it open.

**Comment by Znzero** [comment]
> @Znzero If your question is answered please close the ticket. If you tend to option 2, we can keep it open.
my question is answered, thanks~~
