### ISSUE TITLE
Qt version problem under 5.14 while compling

### ISSUE THREAD

**Issue by asgawa** [COVESA/dlt-viewer#347]
These functions were introduced in Qt 5.14 and they occur build error.
 - Qt::endl https://doc.qt.io/qt-5/qt.html#endl
 - QAtomicInt::loadRelaxed https://doc.qt.io/qt-5/qatomicinteger.html#loadRelaxed

**Comment by asgawa** [comment]
I've already fixed in my local but I don't have branch permission for pull request.

**Comment by alexmucde** [comment]
Hello @asgawa, thanks for your contribution. You have to clone first the dlt-viewer, and then create a branch with your changes. Then push the branch to your clone and then you can create the PR.

**Comment by asgawa** [comment]
OK @alexmucde , I will try. Thanks.

**Comment by asgawa** [comment]
Fixed 7cc40f853d357faa904f89a4203f0c613358d110
