### ISSUE TITLE
Because although I input the capital letters of "NAVC", it will be changed to small letters "navc", so I can't change CCP via DLT tool successfully.

### ISSUE THREAD

**Issue by songsong88** [COVESA/dlt-viewer#361]
Error Description:
when I try to change the CCP via DLT tool, when I input the capital letters of "NAVC", it will change to small letters "navc", so I can't change CCP via DLT tool successfully.
However, in daily testing ,we always need to use the tool to change CCP.
So please help to fix this issue ,thanks!

**Comment by songsong88** [comment]
Let me add more information ,when we try to change CCP via DLT Tool, we need select **"send injection"** at first ,then we need input "NAVC" to Application ID;
input "BLPS" to Context ID;
input ""8002  to Service ID;
at the end , need input the corresponding longitude and dimensions into the "data"(delete the",")

 As from the details ,you can check the below content ,thanks!

•	When we try to change the CCP of the car, we follow the steps below:

 	1.open "dlt viewer shortcut"software
 	2.connect current HU-->Set current HU IP
 	3.after the connect established, tap “config” then you need right click on the line “ECU Online” and select: **send injection**
![image](https://github.com/COVESA/dlt-viewer/assets/137997123/78cee26e-cc2d-4974-9958-38bf2f3aa57f)

 	4.next you will go to the following page:
 
![image](https://github.com/COVESA/dlt-viewer/assets/137997123/31603e09-089f-4471-86d3-7b014c4508cb)
 	5. Paste the correct longitude and dimensions into the "data"(delete the",")
 	6.Click ok, then the CCP should be changed accordingly.

**Comment by alexmucde** [comment]
As a quick fix, you have to remove "navc" from the c:\users\xxxx\.dlt\config\config.ini, when DLT Viewer is not running, then Restart.

As a long term issue this must be fixed.
