### ISSUE TITLE
bug: cannot build dlt-viewer on ubuntu 22.04/flavours

### ISSUE THREAD

**Issue by freitzzz** [COVESA/dlt-viewer#365]
when installing `qt5-default` (sudo apt install qt5-default), apt fails to retrieve the package. this happens because the package was discontinued on focal (20.04) (https://packages.ubuntu.com/focal/qt5-default)

A workaround is to install the packages manually: `sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools`

https://askubuntu.com/a/1395746

**Comment by hannesa2** [comment]
It would make al lot of sense to update CI to 22.04 and apply this in pipelines as well
