### ISSUE TITLE
INSTALL.md says the source has been tested on QT 5.9.5 but it fails

### ISSUE THREAD

**Issue by lordadamson** [COVESA/dlt-viewer#374]
I downloaded Release v2.24.0
followed instructions in the INSTALL.md
installed Qt 5.9.5 (Ubuntu Linux)
tried to build, it still failed because the code tried to access QNetworkInterface::type() which doesn't exist in Qt 5.9.5

The code built successfully when I removed Qt 5.9.5 and installed Qt 5.15.2

**Comment by alexmucde** [comment]
@lordadamson You are right, older Qt versions are not supported anymore, newer versions must be used. Documentation must be updated.

**Comment by alexmucde** [comment]
Fixed on master
