### ISSUE TITLE
Cannot set Maxmum file size of cache dlt file

### ISSUE THREAD

**Issue by liuhangng** [COVESA/dlt-viewer#396]
![image](https://github.com/COVESA/dlt-viewer/assets/17866429/9a856c6c-845d-4118-8088-a181765df359)

As you see, I cannot set this option box with any number, please help me how to iusse it

Best regards

Thanks

**Comment by alexmucde** [comment]
@liuhangng Please check lattest version. This was already fixed.

**Comment by liuhangng** [comment]
![image](https://github.com/COVESA/dlt-viewer/assets/17866429/ef9442e8-6c4e-4bc6-a321-c39e4c995fdf)

OK , thanks so much. This lastest version is very nice!

**Comment by alexmucde** [comment]
Question solved
