### ISSUE TITLE
DLT 2.25.0 won't launch

### ISSUE THREAD

**Issue by bunty95** [COVESA/dlt-viewer#398]
Using the provided "DLT-macOS.zip" and running the DLTViewer program, below is the error that is found.
Seems like the build/packaging is not done correctly.

Possibly due to QT5 being used to build instead of QT6?

Process:               dlt-viewer [8447]
Path:                  /Volumes/VOLUME/*/DLTViewer.app/Contents/MacOS/dlt-viewer
Identifier:            org.genivi.dlt-viewer
Version:               2.25.0 (2.25.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-14 11:29:43.1041 -0500
OS Version:            macOS 12.7.1 (21G920)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        90FE766C-B1B7-0302-5C3A-F87C84E24D45

Sleep/Wake UUID:       9C9C233B-7A95-4937-849A-9CA4F48277AF

Time Awake Since Boot: 68000 seconds
Time Since Wake:       283 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/libqdlt.dylib'
Referenced from: '/Volumes/VOLUME/*/DLTViewer.app/Contents/MacOS/dlt-viewer'
Reason: tried: '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)**

**Comment by aenbeel** [comment]
In case someone else is having the issue, for now I've fixed it by symlinking the library in `/usr/local/lib`:

```
ln -s /Applications/DLTViewer.app/Contents/Frameworks/libqdlt.dylib /usr/local/lib/libqdlt.dylib
```

**Comment by alexmucde** [comment]
@bunty95 Please close ticket if issue is solved.

**Comment by oxoxoxox** [comment]
> In case someone else is having the issue, for now I've fixed it by symlinking the library in `/usr/local/lib`:
> 
> ```
> ln -s /Applications/DLTViewer.app/Contents/Frameworks/libqdlt.dylib /usr/local/lib/libqdlt.dylib
> ```

It worked!
M1Pro, Sonoma 14.4

**Comment by bunty95** [comment]
issue is resolved.

**Comment by zenanswer** [comment]
Works with Apple M1 Pro and Sonoma 14.3.1

**Comment by bunty95** [comment]
Issue still needs to be addressed in the latest master build.
Will close once integrated
