### ISSUE TITLE
Checkbox Selection and Applied Filter Conditions Mismatch (Especially When Using Spacebar)

### ISSUE THREAD

**Issue by Mobilus-HongpyoJang** [COVESA/dlt-viewer#430]
The conditions of the filters applied differ from those of the checkboxes, especially when the filters are checked using the spacebar.

Ver: 2.25.0
Env: Windows 10(19045.3930)
Reproducibility: frequently
Recovery Method : Click check box with mouse cursor

**Comment by alexmucde** [comment]
@Mobilus-HongpyoJang I do not understand your issue. Please provide more details, perhaps also a screenshot.
