### ISSUE TITLE
Dlt viewer is ultimately slow in windows11 

### ISSUE THREAD

**Issue by senthilki** [COVESA/dlt-viewer#457]
Suspecting it might be because of onedrive installed, but I tried to execute the DLT viewer SDK application and input DLT file both in folder which is not handled by onedrive, still dlt viewer is very slow.

**Comment by alexmucde** [comment]
@senthilki I cannot see any performance issue on my Windows PC (Windows 10). I also did not heard any issue of any users so far.
Does anyone else have any issue?

**Comment by alexmucde** [comment]
@senthilki Please reopen, if you have identified the issue.
