### ISSUE TITLE
Notarization of MacOS artifacts

### ISSUE THREAD

**Issue by hannesa2** [COVESA/dlt-viewer#488]
Currently, we can build for MacOS, but we can't start because of missing notarization.
The idea is to do it like https://github.com/gitx/gitx/pull/334/files and for this we need a sponsor for an Apple Developer ID, or someone who fill these variables with the necessary secrets 

<img width="377" alt="image" src="https://github.com/COVESA/dlt-viewer/assets/3314607/7f5488e7-bcc4-42f7-90df-e3e474c46265">

**Comment by bunty95** [comment]
@hannesa2 I have a apple dev account and can help provide most of this info

**Comment by hannesa2** [comment]
@alexmucde as long as we don't have access to this settings for variables, we can't continue here.

**Comment by alexmucde** [comment]
@hannesa2 You mean access to "Actions secrets and variables"?

**Comment by bunty95** [comment]
@hannesa2 can you see if this application is signed and works for you?
https://github.com/bunty95/dlt-viewer/releases/tag/2.26.0.1

**Comment by hannesa2** [comment]
It's not signed jet. We wait for @alexmucde

**Comment by hannesa2** [comment]
> @hannesa2 You mean access to "Actions secrets and variables"?

As discussed in a 1:1 chat: yes

**Comment by bunty95** [comment]
> It's not signed jet. We wait for @alexmucde

Understood, I have signed this app, but need someone to double check on arm64. Could you check and report back for me?
https://github.com/bunty95/dlt-viewer/releases/tag/2.26.0.1 <- DLT-Mac_arm64.zip

**Comment by hannesa2** [comment]
> Is it possible to let us add the secrets? I have notarization working on my fork of this repo.

@alexmucde It's you task to enable someone to do so

**Comment by alexmucde** [comment]
@bunty95 @hannesa2 Please let me know what exactly what to do. We can also do a Teams session together.

**Comment by hannesa2** [comment]
> @bunty95 @hannesa2 Please let me know what exactly what to do. We can also do a Teams session together.

As outcome, you need to give @bunty95 (temporary) admin access, to allow him to add credentials as a variable

**Comment by alexmucde** [comment]
@bunty95  Done, please check if it works.

**Comment by bunty95** [comment]
@alexmucde doesn't look like i am able to add secrets.
Looking at the GitHub docs I will need Admin access. Not sure how to do that.
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions

**Comment by alexmucde** [comment]
Done

**Comment by bunty95** [comment]
Secrets added, tried to update the PR workflow to pull in the secrets but gives me an error.
Using the same commands on my personal fork and it works.
@hannesa2 any idea what might be the issue?

**Comment by hannesa2** [comment]
I see no pull request here https://github.com/bunty95/dlt-viewer/pulls
