### ISSUE TITLE
SOMEIP plugin was not supported in Linux dlt-viewer v2.25.0 version

### ISSUE THREAD

**Issue by wojoin** [COVESA/dlt-viewer#492]
SOMEIP plugin was not supported in the dlt-viewer v2.25.0 version. But SOMEIP plugin was provided in v2.23.0 and I can select the specific fibex version.
At the same time, It is not clear for how to use the command with SOMEIP plugin in Linux or Windows.
v2.25.0
<img width="606" alt="v2 25 0" src="https://github.com/COVESA/dlt-viewer/assets/6468368/933d40c9-aa3d-48c5-b7e0-46526d166a5d">

v2.23.0
<img width="934" alt="v2 23 0" src="https://github.com/COVESA/dlt-viewer/assets/6468368/6ff4cb4f-7fdc-4db7-8913-4744d5ce8b2a">

**Comment by alexmucde** [comment]
@wojoin SOMEIP Plugin was never part of the COVESA distribution of DLT Viewer. Please contact me at BMW if you need more information.

**Comment by alexmucde** [comment]
Please close the ticket if the question is answered.

**Comment by wojoin** [comment]
I got more information from @alexmucde and it's not issue.

**Comment by hannesa2** [comment]
Here is the source https://github.com/COVESA/vsomeip
