### ISSUE TITLE
Payload range search does not work

### ISSUE THREAD

**Issue by vifactor** [COVESA/dlt-viewer#502]
If I set "PayLoad start" and "Payload end" values in the "Search"-dialog no visible changes to the search happens. It can very much happen that I do not understand how this feature suppose to work, but my expectation would be that in search panel if payload "start" and "end" is set, one should see only messages between "start" and "end" matches.

I am trying to make that part of code testable and add actual unit test for it. This is how I found that it does not work as I would expect it. I see no tests in the project. Would you see value in starting such initiative?

**Comment by alexmucde** [comment]
I also do not understand the functionality of Payload start and end. I never used it.
I would appreciate starting writing tests.
Should be then also execute the tests in Github Actions.

**Comment by vifactor** [comment]
@alexmucde what about removing this functionality completely?

**Comment by alexmucde** [comment]
@vifactor Is this solved now?

**Comment by vifactor** [comment]
@alexmucde no, there is still some dead code left. I'll make an MR to clean it up
