### ISSUE TITLE
window command line error

### ISSUE THREAD

**Issue by EdagrHW** [COVESA/dlt-viewer#508]
![image](https://github.com/user-attachments/assets/8a73c4a8-bf3e-4eee-bb86-ec9450b2dcac)

**Comment by EdagrHW** [comment]
@jeremiah

**Comment by jeremiah** [comment]
Hi @jeremiah - I no longer work for GENIVI (which I guess is called 'COVESA' now.) But I imagine the maintainer of DLT ought to be able to help you here. It looks like a configuration issue to me.
