### ISSUE TITLE
Mac App Store Release

### ISSUE THREAD

**Issue by bunty95** [COVESA/dlt-viewer#514]
Since I have a developer account with Apple, should I release DLT Viewer through the Mac App store?
A link to the Mac app store can take care of distribution for signed apps along with the signed apps being posted on github.

Thoughts @hannesa2 and @alexmucde ?

**Comment by hannesa2** [comment]
I at least love the idea. Best with automatic publishing on a new release

**Comment by bunty95** [comment]
Sounds good, I will set it up and add the link in a PR.

**Comment by bunty95** [comment]
DLTViewer is available on Appstore:

https://apps.apple.com/us/app/dlt-viewer/id6648796931

**Comment by hannesa2** [comment]
Thank you. At the one hand it's a nice option for lazy guys 👍

At the other side, it's not an comprehensible build and we don't know the exact source of it. I at least, miss some version info, e.g

![image](https://github.com/user-attachments/assets/d10182fc-6a44-4618-ab8e-14474da48d78)

Unfortunately I'm no qt developer, and for me it's hard to add this. But I guess it's something like this https://github.com/nocnokneo/cmake-git-versioning-example

In general, I would love to let the version artifact built by our CI and upload it from there https://github.com/COVESA/dlt-viewer/issues/488 there we could use brew as source as well

**Comment by hannesa2** [comment]
Any chance to make this work ?

> In general, I would love to let the version artifact built by our CI and upload it from there https://github.com/COVESA/dlt-viewer/issues/488 there we could use brew as source as well

**Comment by bunty95** [comment]
Its a good idea, let me run some tests and see if i can get something like that added to the appstore release.
