### ISSUE TITLE
2.26.1 release file for macOS is empty

### ISSUE THREAD

**Issue by oxoxoxox** [COVESA/dlt-viewer#547]

**Comment by hannesa2** [comment]
Unfortunately yes, but the corresponding master build comes with the binary

**Comment by oxoxoxox** [comment]
> Unfortunately yes, but the corresponding master build comes with the binary

OK, I already download the master build binary from Actions

**Comment by hannesa2** [comment]
But now https://github.com/COVESA/dlt-viewer/actions/runs/11093293490 I see the notarization and codesign is missing  in release.
@bunty95 just to inform you

**Comment by hannesa2** [comment]
Now the release job includes the artifacts https://github.com/COVESA/dlt-viewer/actions/runs/11093436417/job/30819891681, but the release job itself miss it

**Comment by hannesa2** [comment]
Finally the MacOS artifacts are in release https://github.com/COVESA/dlt-viewer/releases/tag/2.26.2 now
But it includes a lot of noise https://github.com/COVESA/dlt-viewer/issues/534
